test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] || SecureRandom.hex(64) %>

development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] || SecureRandom.hex(64) %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
